### ISSUE TITLE
Fabric fork crash on Startup

### ISSUE THREAD

**Issue by Stein123123** [kntrel/Underilla#11]
Hello,

I succesfully compiled the entire main directory with gradle 8.4 using "gradlew buildDependents", coppied the Underilla-Fabric-1.0-SNAPSHOT.jar into the mods folder of my fabric 0.14.24 Server on which I have the Fabric API fabric-api-0.90.7+1.20.2.jar and Chunky-1.3.92.jar installed. 

After changing the Mod ID inside "Underilla-Fabric/src/main/resources/fabric.mod.json" 
from: "id": "Underilla-Fabric", 
to "id": "underilla-fabric" 
in order to fix Fabric not accepting Uppercase letters in ID's I get the Issue:

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'underilla-fabric'.

Here's the full log:
[latest.log](https://github.com/Jeshuakrc/Underilla/files/13404954/latest.log)

I ran the Server with Java 21 and tried Java 17 but neither worked.

If you would like any further Information I'd love to help

**Comment by Jeshuakrc** [comment]
Hey!
Sorry, the Fabric port is a work in progress, and it's not ready for usage. You may self-host a Spigot server, generate the world with the Spigot plugin port and then upload the world to your Fabric server.
